# Generated by Django 4.1.3 on 2022-11-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.BooleanField(default=True)),
                ('date_add', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
                ('picture', models.FileField(upload_to='img_about')),
                ('picture1', models.FileField(upload_to='img_about')),
                ('lebele', models.TextField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('experience', models.IntegerField()),
            ],
            options={
                'verbose_name': 'A propos de nous',
                'verbose_name_plural': 'A propos de nous',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.BooleanField(default=True)),
                ('date_add', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
                ('picture', models.FileField(upload_to='img_banner')),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'bannière',
                'verbose_name_plural': 'bannières',
            },
        ),
        migrations.CreateModel(
            name='ProcessOfConstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.BooleanField(default=True)),
                ('date_add', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
                ('picture', models.FileField(upload_to='img_process')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('order', models.IntegerField()),
            ],
            options={
                'verbose_name': 'procédure de constrution',
                'verbose_name_plural': 'procédure de construtions',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.BooleanField(default=True)),
                ('date_add', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
                ('picture', models.FileField(upload_to='img_service')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.BooleanField(default=True)),
                ('date_add', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('icon', models.CharField(max_length=250)),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'réseau social',
                'verbose_name_plural': 'réseau sociaux',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.BooleanField(default=True)),
                ('date_add', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
                ('picture', models.FileField(upload_to='img_team')),
                ('name', models.CharField(max_length=250)),
                ('work', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'équipe',
                'verbose_name_plural': 'équipes',
            },
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.BooleanField(default=True)),
                ('date_add', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
                ('picture', models.FileField(upload_to='img_testi')),
                ('name', models.CharField(max_length=250)),
                ('work', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'témoignage',
                'verbose_name_plural': 'témoignages',
            },
        ),
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.BooleanField(default=True)),
                ('date_add', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Info du site',
                'verbose_name_plural': 'Infos du site',
            },
        ),
    ]
