# Generated by Django 4.1.3 on 2022-11-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_about_title1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.BooleanField(default=True)),
                ('date_add', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('titleAbout1', models.CharField(max_length=250)),
                ('titleAbout', models.CharField(max_length=250)),
                ('titleService', models.CharField(max_length=250)),
                ('titleRVD', models.CharField(max_length=250)),
                ('titleTestimony', models.CharField(max_length=250)),
                ('libeleNewsletter', models.TextField()),
                ('descriptionRDV', models.TextField()),
                ('descriptionTeam', models.TextField()),
                ('descriptionTesti', models.TextField()),
            ],
            options={
                'verbose_name': 'Configuration du site',
                'verbose_name_plural': 'Configuration du site',
            },
        ),
    ]
