# Generated by Django 4.1.3 on 2022-11-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_configweb'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.BooleanField(default=True)),
                ('date_add', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
                ('libele', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Point fort du site',
                'verbose_name_plural': 'Point fort du site',
            },
        ),
    ]
