# Generated by Django 4.1.3 on 2022-11-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_companyfeatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='order',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
