# Generated by Django 4.1.3 on 2022-11-18 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_appointment_contact_newsletter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Ceux qui nous ont contacté', 'verbose_name_plural': 'Ceux qui nous ont contacté'},
        ),
    ]
