# Generated by Django 4.1.3 on 2022-11-18 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_contact_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Service',
            new_name='service',
        ),
    ]
