# Generated by Django 4.1.3 on 2022-12-24 00:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_service_appointment_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='lebele',
            field=tinymce.models.HTMLField(),
        ),
    ]
