# Generated by Django 4.1.3 on 2022-12-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_about_description_alter_about_lebele'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
